services:
  redis:
    image: redis:7-alpine
    container_name: realtime-chat-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  # Optional: Redis Commander for debugging/monitoring
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: realtime-chat-redis-commander
    hostname: redis-commander
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - debug

volumes:
  redis_data:
